# Generated by Django 3.1.7 on 2021-12-24 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
        migrations.AddField(
            model_name='todo',
            name='upload',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
    ]
