# Generated by Django 3.1.7 on 2021-12-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20211224_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='upload',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
